# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 0, 221, 111))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lbl_plain = QtWidgets.QLabel(self.centralwidget)
        self.lbl_plain.setGeometry(QtCore.QRect(90, 110, 47, 13))
        self.lbl_plain.setObjectName("lbl_plain")
        self.lbl_cipher = QtWidgets.QLabel(self.centralwidget)
        self.lbl_cipher.setGeometry(QtCore.QRect(90, 360, 71, 16))
        self.lbl_cipher.setObjectName("lbl_cipher")
        self.lbl_sign = QtWidgets.QLabel(self.centralwidget)
        self.lbl_sign.setGeometry(QtCore.QRect(580, 360, 71, 16))
        self.lbl_sign.setObjectName("lbl_sign")
        self.lbl_info = QtWidgets.QLabel(self.centralwidget)
        self.lbl_info.setGeometry(QtCore.QRect(580, 110, 71, 16))
        self.lbl_info.setObjectName("lbl_info")
        self.btn_en = QtWidgets.QPushButton(self.centralwidget)
        self.btn_en.setGeometry(QtCore.QRect(220, 570, 75, 23))
        self.btn_en.setObjectName("btn_en")
        self.btn_de = QtWidgets.QPushButton(self.centralwidget)
        self.btn_de.setGeometry(QtCore.QRect(320, 570, 75, 23))
        self.btn_de.setObjectName("btn_de")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(680, 570, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_verify.setGeometry(QtCore.QRect(780, 570, 75, 23))
        self.btn_verify.setObjectName("btn_verify")
        self.btn_gen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen.setGeometry(QtCore.QRect(660, 40, 121, 23))
        self.btn_gen.setObjectName("btn_gen")
        self.txt_plain = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain.setGeometry(QtCore.QRect(150, 110, 281, 181))
        self.txt_plain.setObjectName("txt_plain")
        self.txt_cipher = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher.setGeometry(QtCore.QRect(160, 360, 281, 181))
        self.txt_cipher.setObjectName("txt_cipher")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(660, 350, 281, 181))
        self.txt_sign.setObjectName("txt_sign")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(660, 110, 281, 181))
        self.txt_info.setObjectName("txt_info")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.lbl_plain.setText(_translate("MainWindow", "Plain Text:"))
        self.lbl_cipher.setText(_translate("MainWindow", "Cipher Text:"))
        self.lbl_sign.setText(_translate("MainWindow", "Sign:"))
        self.lbl_info.setText(_translate("MainWindow", "Information:"))
        self.btn_en.setText(_translate("MainWindow", "Encrypt"))
        self.btn_de.setText(_translate("MainWindow", "Decrypt"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_verify.setText(_translate("MainWindow", "Verify"))
        self.btn_gen.setText(_translate("MainWindow", "generate keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
